# Generated by Django 6.0.3 on 2026-03-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='divisions',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
