# Generated by Django 6.0.3 on 2026-03-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0002_professor_divisions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
