# Generated by Django 6.0.3 on 2026-03-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0006_student_profile_pic_alter_attendance_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='assigned_labs', to='labapp.student'),
        ),
    ]
