# Generated by Django 6.0.3 on 2026-03-07 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0007_lab_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel_uploads/')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labapp.division')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labapp.lab')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labapp.professor')),
            ],
        ),
    ]
