# Generated by Django 6.0.3 on 2026-03-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0009_alter_evaluation_experiment_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='prn',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
