# Generated by Django 5.0.6 on 2026-03-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0013_evaluation_viva_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelupload',
            name='file',
            field=models.FileField(max_length=500, upload_to='excel_uploads/'),
        ),
    ]
