# Generated by Django 5.0.6 on 2026-03-14 04:29

import labapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labapp', '0014_alter_excelupload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='manual',
            field=models.FileField(blank=True, null=True, storage=labapp.models.lab_document_storage, upload_to='manuals/'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='syllabus',
            field=models.FileField(blank=True, null=True, storage=labapp.models.lab_document_storage, upload_to='syllabus/'),
        ),
    ]
